export const SHOW_MOVIE_DETAIL = 'SHOW_MOVIE_DETAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';


export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILED = 'FETCH_MOVIE_FAILED';



export const FETCH_TOP_RATED_FAILED = 'FETCH_TOP_RATED_FAILED';
export const FETCH_TOP_RATED_SUCCESS = 'FETCH_TOP_RATED_SUCCESS';
export const FETCH_TOP_RATED_REQUEST = 'FETCH_TOP_RATED_REQUEST';

export const FETCH_ACTION_REQUEST = 'FETCH_ACTION_REQUEST';
export const FETCH_ACTION_SUCCESS = 'FETCH_ACTION_SUCCESS';
export const FETCH_ACTION_FAILED = 'FETCH_ACTION_FAILED';

export const FETCH_COMEDY_REQUEST = 'FETCH_COMEDY_REQUEST';
export const FETCH_COMEDY_SUCCESS = 'FETCH_COMEDY_SUCCESS';
export const FETCH_COMEDY_FAILED = 'FETCH_COMEDY_FAILED';

export const FETCH_HORROR_REQUEST = 'FETCH_HORROR_REQUEST';
export const FETCH_HORROR_SUCCESS = 'FETCH_HORROR_SUCCESS';
export const FETCH_HORROR_FAILED = 'FETCH_HORROR_FAILED';

export const FETCH_ROMANTIC_REQUEST = 'FETCH_ROMANTIC_REQUEST';
export const FETCH_ROMANTIC_SUCCESS = 'FETCH_ROMANTIC_SUCCESS';
export const FETCH_ROMANTIC_FAILED = 'FETCH_ROMANTIC_FAILED';


export const FETCH_DOCUMENTARIES_REQUEST = 'FETCH_DOCUMENTARIES_REQUEST';
export const FETCH_DOCUMENTARIES_SUCCESS = 'FETCH_DOCUMENTARIES_SUCCESS';
export const FETCH_DOCUMENTARIES_FAILED = 'FETCH_DOCUMENTARIES_FAILED';



export const SEARCH_DATA_REQUEST='SEARCH_DATA_REQUEST'
export const SEARCH_DATA_SUCCESS='SEARCH_DATA_SUCCESS'
export const SEARCH_DATA_FAILED='SEARCH_DATA_FAILED'